### PR TITLE
Move web3 wrapper from devDependencies to dependencies. Add Complianc…

### PR DESCRIPTION
**Pull request by AdamDanielKing**
…e and SecurityTokenRegistrar to the Polymath class. Remove SecurityTokenRegistrar's dependency on a SecurityToken.

### CODE REVIEW

**Comment by davekay100** [comment]
it looks good , any idea why the Travis and the netlify are failing? can i merge anyways?

**Comment by ChainSafeSystems** [comment]
@priom what are your thoughts?

**Comment by priom** [comment]
Can u guys work on passing the test? I see there are some changes on the wrappers and tests.

**Review by davekay100 — APPROVED** [review]
looks good, the updates for access to securiyt tokens and templates has been updated, as well as the fixes to the npm module, travis, and netlify . accepting

**Pull request merged**
